name: bayes-rl-mcmc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  - cmake
  - pip:
      - -r setup/requirements.txt
